export type ApiSuccess<T> = {
  data: T;
  meta?: Record<string, unknown>;
  message?: string;
};

export type ApiError = {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
};

export * from '#admin-management/schemas';
export * from '#admin-management/contracts';
export * from '#admin-management/types';
export * from '#patient-management/schemas';
export * from '#patient-management/contracts';
export * from '#patient-management/types';
export * from '#doctor-management/schemas';
export * from '#doctor-management/contracts';
export * from '#doctor-management/types';
export * from '#appointment-management/schemas';
export * from '#appointment-management/contracts';
export * from '#appointment-management/types';
export * from '#emr/schemas';
export * from '#emr/contracts';
export * from '#emr/types';
export * from '#terminology/icd10-chapter';
export * from '#terminology/schemas';
export * from '#terminology/contracts';
export * from '#terminology/types';
export * from '#registration-flow/schemas';
export * from '#registration-flow/contracts';
export * from '#registration-flow/types';
export * from '#billing/schemas';
export * from '#billing/accommodation-nights';
export * from '#billing/contracts';
export * from '#billing/types';
export * from '#bpjs-pcare/schemas';
export * from '#bpjs-pcare/contracts';
export * from '#bpjs-pcare/types';
export * from '#bpjs-antrean/schemas';
export * from '#bpjs-antrean/contracts';
export * from '#bpjs-antrean/types';
export * from '#bpjs-antrean-ws/schemas';
export * from '#bpjs-antrean-ws/contracts';
export * from '#bpjs-antrean-ws/types';
export * from '#satusehat/schemas';
export * from '#satusehat/contracts';
export * from '#satusehat/types';
export * from '#pharmacy-flow/schemas';
export * from '#pharmacy-flow/contracts';
export * from '#pharmacy-flow/types';
export * from '#admission-flow/schemas';
export * from '#admission-flow/contracts';
export * from '#admission-flow/types';
export * from '#room-management/schemas';
export * from '#room-management/contracts';
export * from '#room-management/types';
export * from '#specialty/schemas';
export * from '#specialty/contracts';
export * from '#specialty/types';
export * from '#doctor-patient/schemas';
export * from '#doctor-patient/contracts';
export * from '#doctor-patient/types';
export * from '#auth/schemas';
export * from '#auth/contracts';
export * from '#auth/types';
export * from '#auth/pack-permission-hint';
export * from '#auth/unpack-permission-hint';
export * from '#rbac/schemas';
export * from '#rbac/contracts';
export * from '#rbac/types';
export * from '#ai-chatbot/schemas';
export * from '#ai-chatbot/contracts';
export * from '#ai-chatbot/types';
export * from '#document-management/schemas';
export * from '#document-management/contracts';
export * from '#document-management/types';
export * from '#customer-service/schemas';
export * from '#customer-service/contracts';
export * from '#customer-service/types';
export * from '#feature-entitlement/types';
export * from '#feature-entitlement/catalog';
export * from '#feature-entitlement/schemas';
export * from '#feature-entitlement/contracts';
export * from '#notification/schemas';
export * from '#notification/contracts';
export * from '#notification/types';
export * from '#audit/schemas';
export * from '#audit/contracts';
export * from '#audit/types';
export * from '#user-invitation/schemas';
export * from '#user-invitation/contracts';
export * from '#user-invitation/types';
