export type ApiSuccess<T> = {
  data: T;
  meta?: Record<string, unknown>;
  message?: string;
};

export type ApiError = {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
};

/**
 * One field's refusal inside an error envelope's `details`. The validation
 * pipe lists these per failed field, while the envelope's own message stays
 * the generic "Validation failed" — so these are what a reader needs to see.
 */
export type ApiErrorFieldIssue = {
  /** Dotted path of the field, e.g. `nitku` or `items.0.quantity`; empty when the rule spans the payload. */
  path: string;
  message: string;
};

export * from '#shared/phone-number';
export * from '#shared/phone-number-schema';
export * from '#shared/format-phone-number';
export * from '#admin-management/schemas';
export * from '#admin-management/contracts';
export * from '#admin-management/resolve-user-full-name';
export * from '#admin-management/resolve-user-display-name';
export * from '#admin-management/resolve-clinician-name';
export * from '#admin-management/types';
export * from '#patient-management/schemas';
export * from '#patient-management/contracts';
export * from '#patient-management/types';
export * from '#patient-management/format-patient-address';
export * from '#patient-management/to-patient-age-in-months';
export * from '#patient-management/to-patient-age-in-days';
export * from '#patient-management/resolve-satusehat-link-nik-effect';
export * from '#regions/schemas';
export * from '#regions/contracts';
export * from '#regions/types';
export * from '#doctor-management/schemas';
export * from '#doctor-management/contracts';
export * from '#doctor-management/types';
export * from '#doctor-management/build-doctor-display-name';
export * from '#doctor-management/resolve-missing-doctor-profile-fields';
export * from '#doctor-management/midwife-authority-gated-procedure-codes';
export * from '#doctor-management/resolve-midwife-procedure-authority-kind';
export * from '#maternal-care/types';
export * from '#maternal-care/schemas';
export * from '#maternal-care/contracts';
export * from '#maternal-care/compute-estimated-delivery-date';
export * from '#maternal-care/compute-gestational-age';
export * from '#maternal-care/resolve-trimester';
export * from '#maternal-care/resolve-antenatal-visit-code';
export * from '#maternal-care/number-antenatal-visits';
export * from '#maternal-care/resolve-doctor-visit-requirements';
export * from '#maternal-care/build-trimester-schedule';
export * from '#maternal-care/antenatal-referral-rules';
export * from '#maternal-care/resolve-triggered-referral-rules';
export * from '#maternal-care/build-ten-t-checklist';
export * from '#doctor-credential-option/schemas';
export * from '#doctor-credential-option/contracts';
export * from '#doctor-credential-option/types';
export * from '#doctor-credential-option/split-degree-codes';
export * from '#doctor-credential-option/join-degree-codes';
export * from '#doctor-credential-option/resolve-doctor-credential-value';
export * from '#appointment-management/schemas';
export * from '#appointment-management/contracts';
export * from '#appointment-management/types';
export * from '#emr/schemas';
export * from '#emr/contracts';
export * from '#emr/types';
export * from '#emr/is-child-visit-purpose-required';
export * from '#terminology/icd10-chapter';
export * from '#terminology/schemas';
export * from '#terminology/contracts';
export * from '#terminology/types';
export * from '#registration-flow/schemas';
export * from '#registration-flow/contracts';
export * from '#registration-flow/types';
export * from '#registration-flow/resolve-checkin-window';
export * from '#billing/schemas';
export * from '#billing/accommodation-nights';
export * from '#billing/resolve-consultation-tariff';
export * from '#billing/contracts';
export * from '#billing/types';
export * from '#document-templates/template-variables';
export * from '#document-templates/schemas';
export * from '#document-templates/contracts';
export * from '#document-templates/types';
export * from '#bpjs-pcare/schemas';
export * from '#bpjs-pcare/contracts';
export * from '#bpjs-pcare/types';
export * from '#bpjs-antrean/schemas';
export * from '#bpjs-antrean/contracts';
export * from '#bpjs-antrean/types';
export * from '#bpjs-antrean-ws/schemas';
export * from '#bpjs-antrean-ws/contracts';
export * from '#bpjs-antrean-ws/types';
export * from '#notion-connector/contracts';
export * from '#notion-connector/types';
export * from '#bug-report/types';
export * from '#bug-report/detect-sensitive-data';
export * from '#bug-report/schemas';
export * from '#bug-report/contracts';
export * from '#bug-report/triage-schemas';
export * from '#bug-report/triage-types';
export * from '#laboratory/schemas';
export * from '#laboratory/contracts';
export * from '#laboratory/types';
export * from '#laboratory/compute-lab-flag';
export * from '#laboratory/resolve-lab-reference-range';
export * from '#taxes/schemas';
export * from '#taxes/tax-calendar';
export * from '#taxes/resolve-crossed-turnover-fractions';
export * from '#taxes/contracts';
export * from '#taxes/types';
export * from '#taxes/normalize-npwp';
export * from '#taxes/resolve-npwp-status';
export * from '#taxes/resolve-tax-id-change';
export * from '#taxes/resolve-pp55-eligibility';
export * from '#taxes/resolve-effective-tax-code';
export * from '#taxes/resolve-tax-rate';
export * from '#taxes/to-tax-default-target';
export * from '#taxes/is-faktur-code-allowed';
export * from '#taxes/compute-line-tax';
export * from '#taxes/compute-pp55-monthly-tax';
export * from '#taxes/resolve-tax-report-due-dates';
export * from '#taxes/summarize-ppn-output';
export * from '#taxes/diff-tax-report-totals';
export * from '#satusehat/schemas';
export * from '#satusehat/contracts';
export * from '#satusehat/types';
export * from '#satusehat/resolve-satusehat-service-class-code';
export * from '#pharmacy-flow/schemas';
export * from '#pharmacy-flow/contracts';
export * from '#pharmacy-flow/types';
export * from '#admission-flow/schemas';
export * from '#admission-flow/contracts';
export * from '#admission-flow/types';
export * from '#room-management/schemas';
export * from '#room-management/contracts';
export * from '#room-management/types';
export * from '#specialty/schemas';
export * from '#specialty/contracts';
export * from '#specialty/types';
export * from '#doctor-patient/schemas';
export * from '#doctor-patient/contracts';
export * from '#doctor-patient/types';
export * from '#auth/schemas';
export * from '#auth/contracts';
export * from '#auth/types';
export * from '#auth/pack-permission-hint';
export * from '#auth/unpack-permission-hint';
export * from '#rbac/schemas';
export * from '#rbac/contracts';
export * from '#rbac/types';
export * from '#rbac/clinician-role-codes';
export * from '#rbac/is-clinician-role-code';
export * from '#ai-chatbot/schemas';
export * from '#ai-chatbot/contracts';
export * from '#ai-chatbot/types';
export * from '#document-management/schemas';
export * from '#document-management/contracts';
export * from '#document-management/types';
export * from '#customer-service/schemas';
export * from '#customer-service/contracts';
export * from '#customer-service/types';
export * from '#feature-entitlement/types';
export * from '#feature-entitlement/catalog';
export * from '#feature-entitlement/schemas';
export * from '#feature-entitlement/contracts';
export * from '#notification/schemas';
export * from '#notification/contracts';
export * from '#notification/types';
export * from '#audit/schemas';
export * from '#audit/contracts';
export * from '#audit/types';
export * from '#user-invitation/schemas';
export * from '#user-invitation/contracts';
export * from '#user-invitation/types';
export * from '#organization-structure/schemas';
export * from '#organization-structure/contracts';
export * from '#organization-structure/types';
export * from '#user-offboarding/types';
export * from '#user-offboarding/contracts';
export * from '#document-delivery/schemas';
export * from '#document-delivery/contracts';
export * from '#document-delivery/types';
export * from '#document-delivery/opt-out-keyword';
export * from '#managed-document/schemas';
export * from '#managed-document/contracts';
export * from '#managed-document/types';
export * from '#managed-document/validate-against-type';
export * from '#document-approval/schemas';
export * from '#document-approval/contracts';
export * from '#document-approval/types';
export * from '#document-approval/config';
