-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'AI_PROVIDER_CONFIG_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'AI_PROVIDER_CONFIG_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'AI_PROVIDER_CONFIG_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'AI_PROVIDER_CONFIG_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'AI_PROVIDER_CONNECTION_TESTED';
