-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'BPJS_CONFIG_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'BPJS_CONFIG_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'BPJS_CONFIG_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'BPJS_CONNECTION_TESTED';
