-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'BPJS_ANTREAN_CONFIG_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'BPJS_ANTREAN_CONFIG_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'BPJS_ANTREAN_CONFIG_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'BPJS_ANTREAN_CONNECTION_TESTED';
