import type { AppRule } from './ability';

export const ADMIN_MANAGEMENT_ADMIN_RULES: AppRule[] = [
  { action: 'read', subject: 'User' },
  { action: 'create', subject: 'User' },
  { action: 'update', subject: 'User' },
  { action: 'read', subject: 'Role' },
];

export const ADMIN_MANAGEMENT_READ_ONLY_RULES: AppRule[] = [{ action: 'read', subject: 'User' }];

export const ADMIN_PORTAL_ADMIN_RULES: AppRule[] = [
  ...ADMIN_MANAGEMENT_ADMIN_RULES,
  { action: 'read', subject: 'Patient' },
  { action: 'create', subject: 'Patient' },
  { action: 'update', subject: 'Patient' },
  { action: 'read-identifier', subject: 'Patient' },
  { action: 'read-identifier', subject: 'Doctor' },
  { action: 'assign', subject: 'DoctorPatient' },
  { action: 'unassign', subject: 'DoctorPatient' },
  { action: 'read', subject: 'DoctorPatientActivity' },
  { action: 'read', subject: 'Doctor' },
  { action: 'create', subject: 'Doctor' },
  { action: 'update', subject: 'Doctor' },
  { action: 'write', subject: 'DoctorSchedule' },
  { action: 'read', subject: 'Appointment' },
  { action: 'create', subject: 'Appointment' },
  { action: 'update', subject: 'Appointment' },
  { action: 'cancel', subject: 'Appointment' },
  { action: 'approve', subject: 'Appointment' },
  { action: 'read', subject: 'AppointmentSession' },
  { action: 'update', subject: 'AppointmentSession' },
  { action: 'read', subject: 'Registration' },
  { action: 'create', subject: 'Registration' },
  { action: 'update', subject: 'Registration' },
  { action: 'read', subject: 'Encounter' },
  { action: 'write', subject: 'Encounter' },
  { action: 'read', subject: 'Icd10Code' },
  { action: 'read', subject: 'Icd9cmCode' },
  { action: 'read', subject: 'Medication' },
  { action: 'create', subject: 'Medication' },
  { action: 'update', subject: 'Medication' },
  { action: 'read', subject: 'Prescription' },
  { action: 'write', subject: 'DispenseRecord' },
  { action: 'read', subject: 'Inventory' },
  { action: 'write', subject: 'Inventory' },
  { action: 'read', subject: 'ServiceTariff' },
  { action: 'write', subject: 'ServiceTariff' },
  { action: 'read', subject: 'Invoice' },
  { action: 'write', subject: 'Invoice' },
  { action: 'write', subject: 'Payment' },
  { action: 'create', subject: 'ChatSession' },
  { action: 'read', subject: 'ChatSession' },
  { action: 'delete', subject: 'ChatSession' },
  { action: 'create', subject: 'ChatMessage' },
  { action: 'read', subject: 'ChatMessage' },
  { action: 'read', subject: 'AiProviderConfig' },
  { action: 'write', subject: 'AiProviderConfig' },
  { action: 'manage', subject: 'BpjsConfig' },
  { action: 'sync', subject: 'BpjsReference' },
  { action: 'read', subject: 'BpjsReference' },
  { action: 'manage', subject: 'BpjsMapping' },
  { action: 'check', subject: 'BpjsEligibility' },
  { action: 'read', subject: 'BpjsSubmission' },
  { action: 'retry', subject: 'BpjsSubmission' },
  { action: 'link', subject: 'Satusehat' },
  { action: 'read', subject: 'SatusehatSubmission' },
  { action: 'retry', subject: 'SatusehatSubmission' },
];
